# Site
name: "Erik"
title: "Erik Blog"
description: ""
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
#google_analytics: 'UA-xxxxxxxx-1'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  erik:
    name: Erik
    display_name: Erik    
    avatar: 'assets/images/avatar.png'
    web: https://erik-451.github.io/
    twitter: https://twitter.com/eriik451
    description: "Hi! Im Erik I love computer security and in my spare time I do bug bounty or research.<br>Every day I try to learn something new, no matter how small it is."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
